<a href="https://colab.research.google.com/github/juntae02/AI_Class/blob/main/Ai_1week.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

# Day 1

##파이썬

In [ ]:
## 파이썬 - Container Objects
fruit = ['apple', 'banana', 'orange']
tup = ('apple', 'banana', 'watermelon', 'cucumber')

# 1. 인덱싱 => 값 반환
print(fruit[1])
print(tup[0])

# 2. 슬라이싱 : 컨테이너로 반환
print(fruit[1:2])
print(tup[0:1])   # 출력 주

print("="*50)
# 3. 딕셔너리는 key로 접근
flower_price ={'rose': 10000, 'iris': 3000, 'stargauge': 12000}
print(flower_price.items(), '\n')   # key&value 쌍을 tuple로 묶음. 그리고 그 튜플들을 리스트로 묶음!!
print(flower_price.keys(), '\n')    # key 값들을 리스트로 묶음
print(flower_price.values(), '\n')  # value 값들을 리스트로 묶음

# 4. 딕셔너리 POP
print(flower_price)
# flower_price['daisy'] = flower_price['iris']        # 맨 뒤에 'daisy' 추가
flower_price['daisy'] = flower_price.pop('iris')      # .pop()으로 'iris' 삭제 + 맨 뒤에 'daisy' 추가
print(flower_price)

banana
apple
['banana']
('apple',)
dict_items([('rose', 10000), ('iris', 3000), ('stargauge', 12000)]) 

dict_keys(['rose', 'iris', 'stargauge']) 

dict_values([10000, 3000, 12000]) 

{'rose': 10000, 'iris': 3000, 'stargauge': 12000}
{'rose': 10000, 'stargauge': 12000, 'daisy': 3000}


In [ ]:
## 파이썬 - 함수
# 1. type hint (':' 변수의 자료형, '->' 결과값의 자료형)
def addNum(num1: int, num2: int = -1) -> float:     # num2는 디폴트 값 설정
    sum = num1 + num2
    sub = num1 - num2
    return float(sum), float(sub)
result = addNum(10, 2)      # tuple로 값 받음, 변수 2개이면 따로 저장 가
print("result = ", result)

# ex) def addNum() -> list:
# ex) def addNum() -> list[int]:

result =  (12.0, 8.0)


In [ ]:
## 파이썬 - 클래스
# 부모 클래스
class Calculator:
  def __init__(self, a: int, b: int):
    self.result = 0
    self.a = a
    self.b = b
  def add(self):
    self.result = self.a + self.b
    return self.result

x = Calculator(2, 3)
print(x.add())

# 자식 클래스
class Calculator2(Calculator):
  def __init__(self, a, b, c):
    super().__init__(a, b)
    self.c = c
  def mul(self):
    self.result = self.a * self.b
    return self.result

  # 객체 호출 함수
  def __str__(self):
    return str(self.c)
  # 같은 의미
  # def __call__(self):   => numpy
  # def __forward(self):  => torch

x2 = Calculator2(2, 3, 7)
print(x2.add())
print(x2.mul())
print(x2)

5
5
6
7


##넘파이

In [ ]:
## 넘파이 생성 1
x1 = np.array(5)
x2 = np.array([5, 7, 9])
print(x1)
print(x2)

5
[5 7 9]


In [ ]:
## 얕은 복사와 깊은 복사
# 1. 얕은 복사: 주소 복사
y = x2
x2[1] = -1
print(x2, "||", y)    # x 변하면 y도 변환, 반대 상황도 같음

# 2. 깊은 복사 : 값 복사    => x와 y는 별개로 변환
y = x2.copy()
x2[1] = 7
print(x2, "||", y)

[ 5 -1  9] || [ 5 -1  9]
[5 7 9] || [ 5 -1  9]
[5 7 9] || [ 5 -1  3]


In [ ]:
## 넘파이 생성 2
x = np.arange(-2, 2, 0.25)  # -2부터 2까지 0.25 간격
print(x)

[-2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75]


In [ ]:
## 넘파이 생성 3
np.linspace(0, 10, 100) # 찾아보기

## 텐서

In [ ]:
## 텐서 생성
# 텐서 생성하면 float?? 1.
x1 = torch.ones(5)
print(x1)   # 5개

x2 = torch.ones(2, 3)
print(x2)   # 2행 3열, 2차원

x3 = torch.ones(2, 3, 2)
print(x3)   # 3행 2열이 2개, 3차원

tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [ ]:
## 텐서 -> 넘파이
x2 = x1.data.numpy() # 주소 복사

x3 = x1.data.numpy().copy() # 값만 복사

x1[1] = -1 # 인덱싱과 슬라이싱 둘 다 가능

print(x1)
print(type(x1))
print()
print(x2)    # x1값을 변경하면, x2도 변경 됨 (주소를 복사해서)
print(x3)    # x1값을 변경해도 x3는 변경 안됨 (값을 복사해서)
print(type(x2))
print(type(x3))


tensor([ 1., -1.,  1.,  1.,  1.])
<class 'torch.Tensor'>

[ 1. -1.  1.  1.  1.]
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## 매트플롯립

In [ ]:
# 서브플롯 생성 함수, (행, 수, 서브플롯의 위치)
# ax = plt.subplot(nrows, ncols, index)
ax1 = plt.subplot(2, 2, 1)
ax1.plot(x, y1, color='blue')

# 데이터를 그래프 그리는 함수
plt.plot(x, y)

# 클래스로 원 생성
patches.Circle(xy=(self.x, self.y), radius=self.r, fc='b', ec='k')
# (xy = (원의 중심 좌표), radius=반지름)
# 생성된 원을 Axes에 추가
ax.add_patch(c)